// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(InventarioContext))]
    [Migration("20230926055900_initialCreat")]
    partial class initialCreat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Core.entities.Estado", b =>
                {
                    b.Property<string>("codEstado")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombreEstado")
                        .HasColumnType("longtext");

                    b.HasKey("codEstado");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("Core.entities.Pais", b =>
                {
                    b.Property<string>("codPais")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombrePais")
                        .HasColumnType("longtext");

                    b.HasKey("codPais");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("Core.entities.Region", b =>
                {
                    b.Property<string>("codRegion")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombreRegion")
                        .HasColumnType("longtext");

                    b.HasKey("codRegion");

                    b.ToTable("Regiones");
                });
#pragma warning restore 612, 618
        }
    }
}
